web/src/components/TranslateTask.vue
=> web: show log message(title) on title of log detail modal

web/src/components/CSelectNumber.vue, web/src/data/stores/reader_setting.ts, web/src/pages/reader/components/ReaderSettingModal.vue, web/src/pages/reader/components/WebReaderContent.vue
=> web: allow disable extra line spacing in web reader

server/src/main/kotlin/api/RouteWebNovel.kt, server/src/main/kotlin/infra/web/WebNovelMetadataRepository.kt, web/src/pages/list/WebNovelList.vue, web/src/pages/list/components/ListFilters.vue, web/src/pages/list/components/NovelList.vue
=> add multi source search

web/src/data/stores/reader_setting.ts, web/src/layouts/MainLayout.vue, web/src/layouts/ReaderLayout.vue, web/src/pages/reader/components/ReaderContent.vue, web/src/pages/reader/components/ReaderSettingModal.vue, web/src/pages/reader/components/util.ts
=> web: reader support os theme

web/src/data/translator/db/personal.ts, web/src/pages/workspace/components/GlossaryButton.vue
error message: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': #<Object> could not be cloned. 
glossary is a Proxy object
=> web: fix update glossary

web/src/App.vue, web/src/layouts/ReaderLayout.vue, web/src/pages/reader/Reader.vue
router-view 上的 :key 属性导致了动态路由组件无法复用当前组件
将 currentChapterId 改成 computed 属性，使用 router.push 推动 params 变化
=> web: fix reader navigate back bug

web/src/pages/components/ImageCard.vue, web/src/pages/reader/components/ReaderContent.vue
=> web: Add lazy loading to image cards

web/index.html
网页在初次加载或页面刷新的时候，会丢失body颜色，导致页面会出现闪烁的白屏
在body还没生成前优先把style写进页面，防止背景闪烁白屏
=> web: fit body background color

web/src/data/stores/read_position.ts, web/src/model/Common.ts, web/src/pages/reader/Reader.vue, web/src/pages/reader/components/ReaderContent.vue
添加了回到上次阅读位置的功能
第一次用pull request。
=> add go back to the last reading position

web/src/router.ts
修复 Safari 侧滑手势时出现的灰色背景
参考了 react.dev 代码
https://github.com/reactjs/react.dev/blob/e45ac5552c13fc50832624b7deb0c6f631d461bf/src/pages/_app.tsx#L30
https://github.com/FishHawk/auto-novel/assets/32838658/1dbb725a-ce7f-4dac-b7b6-cb787bf8b2c9
=> fix: Safari grey screen during the back swipe gesture

web/package.json, web/pnpm-lock.yaml, web/src/App.vue, web/src/pages/workspace/GptWorkspace.vue, web/src/pages/workspace/SakuraWorkspace.vue, web/src/pages/workspace/components/JobQueue.vue, web/src/pages/workspace/components/JobWorker.vue
支持拖拽排序
目前改了 gpt 和 sakura 工作区的翻译器列表与任务队列
=> feat: support drag sort

web/src/pages/components/CXScrollbar.vue, web/src/pages/novel/WenkuNovel.vue
=> feat(web): x-scrollbar draggable

web/src/pages/novel/WebNovel.vue, web/src/pages/novel/components/WebNovelTocItem.vue
=> fix(web): visited anchor color

web/src/pages/reader/components/ReaderContent.vue
=> feat(web): enhance read position

server/src/main/kotlin/infra/wenku/WenkuNovelMetadataRepository.kt
=> fix: fix updateAt when upload wenku novel

web/src/pages/workspace/components/LocalVolumeList.vue, web/src/pages/workspace/components/LocalVolumeListComposite.vue
支持全屏拖入文件
后续也可以单独提取成一个全屏上传组件，在其他地方复用
=> feat: support fullscreen drag zone

README.md
之前在 TG 群里有发现 `pnpm install` 会修改 yaml 文件。所以用 `pnpm install --frozen-lockfile` 比较好，所以修改一下 readme。
=> doc: update readme with correct instructions

web/src/pages/list/FavoriteList.vue, web/src/pages/novel/components/WebTranslate.vue, web/src/pages/novel/components/WenkuVolume.vue, web/src/pages/workspace/components/LocalVolumeListCompositeItem.vue, web/src/pages/workspace/components/LocalVolumeListSpecificTranslation.vue
把按住 Ctrl 可以置顶任务的功能加到别的几个 “排队Sakura” 按钮上。
参见 #48。
=> feat(web): tops job when queueing if ctrl is held for wenku and local volumes

web/tests/provider.test.ts
=> fix(web): update import path for parseUrl function

web/.husky/pre-commit, web/.prettierrc, web/package.json, web/pnpm-lock.yaml, web/src/domain/smart-import/index.ts
提交前对改动的内容自动进行 prettier 格式化
后续代码更改都会以 .prettierrc 里的配置为准，你看下是否需要调整这个配置文件，修改成自己喜欢的样式
=> chore(web): add pre-commit hook for code formatting

web/src/pages/workspace/components/LocalVolumeList.vue
https://github.com/FishHawk/auto-novel/issues/52
=> feat(web): Search Spaces are supported, and both English and Chinese commas are supported  in local novel

web/src/pages/components/OrderSort.vue, web/src/pages/workspace/components/LocalVolumeList.vue
https://github.com/FishHawk/auto-novel/issues/52
=> feat(web): Local novels added in ascending order descending order

web/src/pages/workspace/components/JobTaskLink.vue, web/src/pages/workspace/components/LocalVolumeListSpecificTranslation.vue
https://github.com/FishHawk/auto-novel/issues/57
=> feat(web): Optimize workspace local novel reading logic

web/src/data/stores/SettingRepository.ts, web/src/model/Setting.ts, web/src/pages/components/CPage.vue, web/src/pages/other/AccountCenter.vue, web/src/pages/workspace/components/LocalVolumeList.vue
改动
- 增加 loading 状态
- 增加 pagination/scroll 两种模式
- 账户页面增加选项`自适应/分页/滚动`，默认自适应，手机使用滚动，电脑使用分页
=> feat(web): infinite scroll load

web/src/data/stores/SettingRepository.ts, web/src/model/Setting.ts, web/src/pages/components/CPage.vue
=> refactor(web): update paginationMode to 'pagination'

web/src/pages/bookshelf/components/BookshelfMenu.vue
https://github.com/FishHawk/auto-novel/issues/71
=> fix(web): Favorites cannot scroll

web/src/model/Translator.ts, web/src/pages/workspace/SakuraWorkspace.vue, web/src/pages/workspace/components/JobRecord.vue
https://github.com/FishHawk/auto-novel/issues/60
=> feat(web): The task record added the completion time

web/src/pages/bookshelf/BookshelfLocalStore.ts, web/src/pages/components/SearchInput.vue, web/src/pages/workspace/components/JobRecordSection.vue, web/src/pages/workspace/components/JobWorker.vue, web/src/pages/workspace/components/LocalVolumeList.vue, web/src/util/index.ts
=> feat(web): Added batch download and search for task records

web/src/pages/bookshelf/components/BookshelfLocalList.vue
=> feat(web): my favorites: local novels use the Unified File search input box

web/src/pages/components/CButton.vue, web/src/pages/workspace/components/LocalVolumeList.vue
优化c-button组件加载行为
调整为执行action时显示loading执行中
=> optimize(web): optimize the loading behavior of the c-button component

README.md
=> doc: readme adds participation in co-build statistics

web/src/pages/home/components/PanelWebNovel.vue
https://github.com/FishHawk/auto-novel/issues/47
=> feat(web): adjust the home page network novel display

web/src/pages/list/components/InputWithSuggestion.vue
使用儲存的tag搜尋紀錄，第一個tag前面也會自帶空格，把這修掉
=> Fixed little problem about webnovel searchbox

web/src/pages/reader/components/CatalogModal.vue
=> feat(web): modify the mouse cursor of the chapter title

web/src/pages/workspace/Katakana.vue
=> fix(web): 术语表次数可能为负数

web/src/domain/translate/TranslatorSakura.ts
=> Update SakuraV1.0 Competibility

web/src/pages/components/CommentList.vue
- 评论区加 loading 动画
- 自动滚动到评论栏顶部，loading结束后处理页面位置，防止页面滚动位置跳跃
=> feat(web): comment list show loading animation & scroll to top

web/src/pages/components/Markdown.vue, web/src/router.ts
- 用新标签打开链接，和评论区保持一致
- 优化滚动行为，确保锚点跳转正常使用，避免顶部App Bar遮挡
- markdown样式优化，避免部分文本超出屏幕
示例文章
https://books.fishhawk.top/forum/66fc22dfac7fc26a59377267
=> feat(web): 优化论坛链接打开方式与锚点定位

web/src/components/ChapterTocItem.vue, web/src/components/ChapterTocList.vue, web/src/data/setting/Setting.ts, web/src/pages/novel/components/UseTocExpansion.ts, web/src/pages/novel/components/WebNovelNarrow.vue, web/src/pages/novel/components/WebNovelWide.vue, web/src/pages/other/Setting.vue, web/src/pages/reader/components/CatalogModal.vue
=> feat(web): 使用 Collapse 重构章节目录

web/src/components/comment/CommentItem.vue, web/src/components/comment/CommentThread.vue, web/src/data/index.ts, web/src/data/stores/BlockUserCommentRepository.ts, web/src/data/stores/index.ts
看到论坛这个[帖子](https://books.fishhawk.top/forum/67f0cc76cfb7be4c00b8a8ba)
单纯按照用户名过滤不显示
=> feat(web): 手动屏蔽部分用户评论

CONTRIBUTING.md, README.md, server/src/main/kotlin/Application.kt, server/src/main/kotlin/infra/web/datasource/WebNovelHttpDataSource.kt, server/src/main/kotlin/infra/web/datasource/providers/Hameln.kt, web/package.json
=> chore(doc): add contributing.md

web/src/components/CModal.vue, web/src/data/setting/Setting.ts, web/src/pages/reader/components/BuildParagraphs.ts, web/src/pages/reader/components/ReaderContent.vue, web/src/pages/reader/components/ReaderSettingModal.vue
=> feat(web): 为阅读器添加文本下划线样式选项

server/src/main/kotlin/infra/web/repository/WebNovelChapterRepository.kt
=> fix(server): 更新翻译数量时校验章节是否在目录内

server/src/main/kotlin/api/RouteUserFavoredWeb.kt, server/src/main/kotlin/infra/web/repository/WebNovelFavoredRepository.kt, web/src/data/favored/FavoredApi.ts, web/src/pages/bookshelf/BookshelfWeb.vue, web/src/router.ts
=> #211 收藏夹内搜索, Part 2: 网络收藏夹小说搜索 前端+后端

.gitignore, docker-compose.yml, server/src/main/kotlin/Application.kt, server/src/main/kotlin/infra/EmailClient.kt
加入環境變數控制
1. MAILGUN_API_ENDPOINT
2. MAILGUN_FROM
調整對應代碼引入環境變數
=> MAILGUN API引入環境變數設置

web/src/pages/list/ReadHistoryList.vue
=> feat(web): 阅读记录清空增加二次确认

web/src/pages/reader/components/ReaderLayoutMobile.vue
=> feat(web): 扩大阅读翻页的点击区域

web/src/pages/forum/ForumArticle.vue, web/src/pages/other/Setting.vue, web/src/pages/other/components/UserBlockButton.vue
[来源](https://n.novelia.cc/forum/685f9fd608b7581278d3256e)
目前存在的问题:
- 修改后概率无法同步到localstorage
因为有了集中贴，先暂时关闭看能否再优化或者有更好的方案
=> feat(web): Setting页面提供黑名单管理

server/build.gradle.kts, server/src/main/kotlin/util/epub/Epub.kt, server/src/main/kotlin/util/epub/ZipUtils.kt
Use zip4j to handle epub files.
Use JimFS to do in memory zip decompress.
Close #251
=> fix(server): use zip4j to handle epub files
